mutation addClient(
  $name: String!
  $content: String!
  $phone: String!
  $interestLevel: String
) {
  createClient(
    data: {
      name: $name
      content: $content
      phone: $phone
      interestLevel: $interestLevel
    }
  ) {
    id
    name
  }
}
